import { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import { useCorridas } from '../contexts/CorridasContext';
import { supabase } from '@/integrations/supabase/client';
import { type Corrida } from '../types/corridas';

export interface CorridaFinanceiro {
  id: number;
  empresa: string;
  motorista: string;
  veiculo?: string;
  dataServico: string;
  origem: string;
  destino: string;
  kmTotal: number;
  valor: number;
  valorMotorista?: number;
  status: 'Aguardando Conferência' | 'Em Análise' | 'No Show' | 'Revisar' | 'Cancelada' | 'Aprovada';
  statusPagamento: 'Pendente' | 'Pago';
  medicaoNotaFiscal: 'Medição' | 'Nota Fiscal';
  observacoes?: string;
  motivoReprovacao?: string;
  dataConferencia?: string;
  conferenciadoPor?: string;
  centroCusto: string;
  pedagio: number;
  estacionamento: number;
  hospedagem: number;
  passageiros: string;
  destinoExtra: string;
  numeroOS: string;
  projeto?: string;
  motivo?: string;
  horaInicio?: string;
  horaOS?: string;
  horaEspera?: string;
  valorHoraEspera?: number;
  cteNf?: string;
  horaFim?: string;
  kmInicial?: number;
  kmFinal?: number;
  solicitante?: string;
  tipoAbrangencia?: string;
}

export const useFinanceiro = () => {
  const { corridas: corridasOriginais, updateStatus: updateCorridaStatus, updateCorrida: updateCorridaOriginal } = useCorridas();
  
  // Filtrar corridas para conferência financeira: incluir recém-cadastradas e já preenchidas
  const corridasParaFinanceiro = corridasOriginais.filter(corrida => 
    // Incluir corridas já preenchidas pelo motorista
    corrida.status === 'Aguardando Conferência' || 
    corrida.preenchidoPorMotorista === true || 
    (!!corrida.numeroOS && String(corrida.numeroOS).trim() !== '') ||
    // Incluir corridas recém-cadastradas que ainda não foram preenchidas
    corrida.status === 'Aguardando OS' ||
    corrida.status === 'Selecionar Motorista' ||
    corrida.status === 'Pendente' ||
    // Incluir corridas editadas pelo financeiro
    (corrida as any).preenchidoPorFinanceiro === true
  );
  
  // Converter corridas do formato original para o formato do financeiro com TODOS os dados
  const baseCorridas: CorridaFinanceiro[] = useMemo(() => {
    return corridasParaFinanceiro.map(corrida => {
      const statusMapeado = mapStatusToFinanceiro(corrida.status);
      
      return {
        id: corrida.id,
        empresa: corrida.empresa,
        motorista: corrida.motorista || '',
        veiculo: (corrida as any).veiculo || '',
        dataServico: (corrida as any).dataServico || corrida.data,
        origem: corrida.origem,
        destino: corrida.destino,
        kmTotal: corrida.kmTotal || 0,
        valor: corrida.valor || 0,
        valorMotorista: corrida.valorMotorista || 0,
        status: statusMapeado,
        statusPagamento: (corrida as any).statusPagamento || 'Pendente',
        medicaoNotaFiscal: (corrida as any).medicaoNotaFiscal || 'Medição',
        observacoes: corrida.observacoes,
        centroCusto: corrida.centroCusto || '',
        pedagio: corrida.pedagio || 0,
        estacionamento: corrida.estacionamento || 0,
        hospedagem: corrida.hospedagem || 0,
        passageiros: (corrida as any).passageiros || '',
        destinoExtra: corrida.destinoExtra || '',
        numeroOS: corrida.numeroOS || '',
        projeto: corrida.projeto,
        motivo: corrida.motivo,
        horaInicio: (corrida as any).horaInicio || (corrida as any).horaSaida,
        horaOS: (corrida as any).horaOS || (corrida as any).hora_os,
        horaEspera: (corrida as any).horaEspera || (corrida as any).hora_espera,
        valorHoraEspera: (corrida as any).valorHoraEspera || (corrida as any).valor_hora_espera,
        cteNf: (corrida as any).cteNf || (corrida as any).cte_nf,
        horaFim: (corrida as any).horaFim || (corrida as any).horaChegada || (corrida as any).hora_chegada,
        tipoAbrangencia: (corrida as any).tipoAbrangencia,
        kmInicial: corrida.kmInicial,
        kmFinal: corrida.kmFinal,
        solicitante: corrida.solicitante
      };
    });
  }, [corridasParaFinanceiro]);

  const corridas = baseCorridas;

  // Obter lista única de empresas
  const empresas = useMemo(() => {
    const empresasUnicas = new Set(corridas.map(c => c.empresa).filter(Boolean));
    return Array.from(empresasUnicas).sort();
  }, [corridas]);

  // Função para filtrar por empresa
  const filterByEmpresa = (list: CorridaFinanceiro[], empresa: string) => {
    if (!empresa || empresa === 'all') return list;
    return list.filter((c) => c.empresa === empresa);
  };

  // Função para filtrar por passageiros (busca fuzzy)
  const filterByPassageiros = (list: CorridaFinanceiro[], searchTerm: string) => {
    if (!searchTerm || searchTerm.length < 3) return list;
    
    const searchLower = searchTerm.toLowerCase();
    return list.filter(corrida => {
      const passageiros = corrida.passageiros.toLowerCase();
      // Busca por palavras similares - divide o termo de busca e os passageiros em palavras
      const searchWords = searchLower.split(/\s+/);
      const passageiroWords = passageiros.split(/[,;:\s]+/);
      
      return searchWords.some(searchWord => 
        passageiroWords.some(passageiroWord => 
          passageiroWord.includes(searchWord) || searchWord.includes(passageiroWord)
        )
      );
    });
  };

  // Função para mapear status entre os tipos
  function mapStatusToFinanceiro(status: Corrida['status']): CorridaFinanceiro['status'] {
    switch (status) {
      case 'OS Preenchida':
      case 'Pendente':
      case 'Aguardando Conferência':
        return 'Aguardando Conferência';
      case 'Aprovada':
        return 'Aprovada';
      case 'No Show':
        return 'No Show';
      case 'Rejeitada':
        return 'Revisar';
      case 'Cancelada':
        return 'Cancelada';
      default:
        return 'Em Análise';
    }
  }

  const updateStatus = (corridaId: number, status: CorridaFinanceiro['status']) => {
    // Mapear status do financeiro para o contexto de corridas
    let corridaStatus: Corrida['status'];
    switch (status) {
      case 'Aguardando Conferência':
        corridaStatus = 'Aguardando Conferência';
        break;
      case 'Aprovada':
        corridaStatus = 'Aprovada';
        break;
      case 'Revisar':
        corridaStatus = 'Rejeitada';
        break;
      case 'Cancelada':
        corridaStatus = 'Cancelada';
        break;
      case 'Em Análise':
        corridaStatus = 'Em Análise';
        break;
      case 'No Show':
        corridaStatus = 'No Show';
        break;
      default:
        corridaStatus = 'Em Análise';
    }
    
    updateCorridaStatus(corridaId, corridaStatus);
    toast.success(`Status alterado para ${status}!`);
  };

  const updatePaymentStatus = async (corridaId: number, statusPagamento: CorridaFinanceiro['statusPagamento']) => {

    await updateCorridaOriginal(corridaId, { statusPagamento });
    toast.success(`Status de pagamento alterado para ${statusPagamento}!`);
  };

  const updateMedicaoNotaFiscalStatus = async (corridaId: number, medicaoNotaFiscal: CorridaFinanceiro['medicaoNotaFiscal']) => {

    await updateCorridaOriginal(corridaId, { medicaoNotaFiscal });
    toast.success(`Status de medição/nota fiscal alterado para ${medicaoNotaFiscal}!`);
  };

  const updateCorrida = async (corridaId: number, updatedData: any, documentos: any[]) => {
    try {
  
      // Atualiza dados básicos da corrida usando o contexto e aguarda persistência
      await updateCorridaOriginal(corridaId, updatedData);

      // Processa documentos (se houver)
      if (Array.isArray(documentos) && documentos.length > 0) {
        for (const documento of documentos) {
          if (!documento?.arquivo) continue;
          try {
            const fileExtension = documento.arquivo.name.split('.').pop();
            const safeNome = String(documento.nome || 'comprovante').toLowerCase().replace(/\s+/g, '-');
            const fileName = `${corridaId}/${safeNome}-${Date.now()}.${fileExtension}`;

            const { data: uploadData, error: uploadError } = await supabase.storage
              .from('corrida-documentos')
              .upload(fileName, documento.arquivo);

            if (uploadError) {
              console.error('Erro no upload do arquivo:', uploadError);
              continue;
            }

            const { error: dbError } = await supabase
              .from('corrida_documentos')
              .insert({
                corrida_id: corridaId,
                nome: documento.nome,
                descricao: documento.descricao,
                url: uploadData?.path
              });

            if (dbError) {
              console.error('Erro ao salvar metadados do documento:', dbError);
              // Em caso de erro ao salvar metadados, remove o arquivo enviado
              if (uploadData?.path) {
                await supabase.storage.from('corrida-documentos').remove([uploadData.path]);
              }
            }
          } catch (docErr) {
            console.error('Erro inesperado ao processar documento:', docErr);
          }
        }
      }

      toast.success('Corrida atualizada com sucesso!');
    } catch (error) {
      console.error('Erro ao atualizar corrida:', error);
      toast.error('Erro ao atualizar corrida');
      throw error;
    }
  };

  const approveCorrida = async (corrida: CorridaFinanceiro) => {
    // Atualiza status e marca data de conferência

    updateStatus(corrida.id, 'Aprovada');
    await updateCorridaOriginal(corrida.id, {
      dataConferencia: new Date().toISOString(),
      motivoReprovacao: null
    } as any);
    toast.success('Corrida aprovada com sucesso!');
  };

  const rejectCorrida = async (corrida: CorridaFinanceiro, motivo: string) => {

    updateStatus(corrida.id, 'Revisar');
    await updateCorridaOriginal(corrida.id, {
      motivoReprovacao: motivo
    } as any);
    toast.success('Corrida enviada para revisão!');
  };

  // Utilitários de data para estatísticas mensais
  const parseDateFromString = (s?: string): Date | null => {
    if (!s) return null;
    // Tenta parse nativo (ISO, RFC, etc.)
    const native = new Date(s);
    if (!isNaN(native.getTime())) return native;
    // Tenta DD/MM/YYYY
    const m = s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);
    if (m) {
      const [_, dd, mm, yyyy] = m;
      const d = new Date(Number(yyyy), Number(mm) - 1, Number(dd));
      return isNaN(d.getTime()) ? null : d;
    }
    return null;
  };

  const isSameMonth = (d: Date | null, ref: Date) => {
    if (!d) return false;
    return d.getMonth() === ref.getMonth() && d.getFullYear() === ref.getFullYear();
  };

  const getStats = () => {
    const now = new Date();

    const pendingCount = corridas.filter(c => c.status === 'Aguardando Conferência').length;

    // Contagens mensais para refletir o rótulo "Este mês"
    const approvedCount = corridas.filter(c => c.status === 'Aprovada' && isSameMonth(parseDateFromString(c.dataServico), now)).length;
    const rejectedCount = corridas.filter(c => c.status === 'Revisar' && isSameMonth(parseDateFromString(c.dataServico), now)).length;

    const totalValue = corridas
      .filter(c => c.status === 'Aprovada' && isSameMonth(parseDateFromString(c.dataServico), now))
      .reduce((sum, c) => sum + (c.valor ?? 0), 0);

    return { pendingCount, approvedCount, rejectedCount, totalValue };
  };

  return {
    corridas,
    empresas,
    filterByEmpresa,
    filterByPassageiros,
    updateStatus,
    updatePaymentStatus,
    updateMedicaoNotaFiscalStatus,
    approveCorrida,
    rejectCorrida,
    getStats,
    updateCorrida
  };
};
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
    // ... existing code ...
