// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhucgxcyigkzubnnspki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodWNneGN5aWdrenVibm5zcGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzcwNTksImV4cCI6MjA2ODk1MzA1OX0.oAM8FkvG7SKBZXKlMmDFw6VkrTcTmp2f5pieWeTdJEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});